name: CI Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specifying a compatible Node.js version
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    
    - name: Build backend only
      run: ./gradlew :assemble -x :client-app:yarn_build
      
    - name: Test backend only
      run: ./gradlew :test -x :client-app:yarn_test
